# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.setEnabled(True)
        MainWindow.resize(540, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(540, 107))
        MainWindow.setMaximumSize(QtCore.QSize(540, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName('centralwidget')
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 110, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName('pushButton')
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 511, 81))
        self.textEdit.setToolTip('')
        self.textEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName('textEdit')
        self.logEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.logEdit.setEnabled(True)
        self.logEdit.setGeometry(QtCore.QRect(10, 150, 511, 231))
        self.logEdit.setToolTip('')
        self.logEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.logEdit.setAcceptRichText(False)
        self.logEdit.setObjectName('logEdit')
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate('MainWindow', 'Parce links'))
        self.pushButton.setText(_translate('MainWindow', 'Go!'))
        self.textEdit.setPlaceholderText(_translate('MainWindow', 'Посилання на сторінки (одне на рядок):'))
        self.logEdit.setPlaceholderText(_translate('MainWindow', 'Log:'))
